# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{mongoid_session_store}
  s.version = "1.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ryan Fitzgerald"]
  s.date = %q{2011-03-25}
  s.description = %q{store rails 3 sessions in mongoDB}
  s.email = %q{ryan@codebrewstudios.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "example/.gitignore",
    "lib/mongoid_session_store.rb",
    "lib/mongoid_session_store/mongoid_store.rb",
    "lib/mongoid_session_store/railtie.rb",
    "lib/mongoid_session_store/railties/sessions.rake",
    "mongoid_session_store.gemspec",
    "test/helper.rb",
    "test/test_mongoid_session_store.rb"
  ]
  s.homepage = %q{https://github.com/codebrew/mongoid_session_store}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{store rails 3 sessions in mongoDB}
  s.test_files = [
    "test/helper.rb",
    "test/test_mongoid_session_store.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<actionpack>, ["<= 3.1.0.rc4"])
      s.add_runtime_dependency(%q<activemodel>, ["<= 3.1.0.rc4"])
      s.add_runtime_dependency(%q<mongoid>, ["~> 2.0.0.pre"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_runtime_dependency(%q<actionpack>, ["<= 3.1.0.rc4"])
      s.add_runtime_dependency(%q<activemodel>, ["<= 3.1.0.rc4"])
      s.add_runtime_dependency(%q<mongoid>, ["~> 2.0.0.pre"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<actionpack>, ["<= 3.1.0.rc4"])
      s.add_dependency(%q<activemodel>, ["<= 3.1.0.rc4"])
      s.add_dependency(%q<mongoid>, ["~> 2.0.0.pre"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<actionpack>, ["<= 3.1.0.rc4"])
      s.add_dependency(%q<activemodel>, ["<= 3.1.0.rc4"])
      s.add_dependency(%q<mongoid>, ["~> 2.0.0.pre"])
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<actionpack>, ["<= 3.1.0.rc4"])
    s.add_dependency(%q<activemodel>, ["<= 3.1.0.rc4"])
    s.add_dependency(%q<mongoid>, ["~> 2.0.0.pre"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<actionpack>, ["<= 3.1.0.rc4"])
    s.add_dependency(%q<activemodel>, ["<= 3.1.0.rc4"])
    s.add_dependency(%q<mongoid>, ["~> 2.0.0.pre"])
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

